version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(module)s|%(levelname)s: %(message)s'
  detailed:
    format: '[%(levelname)s|%(module)s|L%(lineno)d|%(name)s] %(asctime)s: %(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%S%z'
  json:
    (): logger_config.MyJSONFormatter
    fmt_keys:
      level: levelname
      message: message
      timestamp: timestamp
      logger: name
      module: module
      line: lineno
handlers:
  stderr:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stderr
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/my_app.log
    maxBytes: 1048576
    backupCount: 3
  file_json:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/my_app.jsonl
    maxBytes: 1048576
    backupCount: 3
root:
  level: DEBUG
  handlers: [stderr, file, file_json]